### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by zz-2024** [wangyifan2018/CLIP-TPU#1]
我在进行第6步推理时，出现问题：
```
(clip)XXX@junqian-Tower-X:~/projects/python/CLIP-TPU$ python3 embeddings_bmcv.py --img_dir ./datasets/imagenet_val_1k --image_model ./models/BM1684X/clip_image_vitb32_bm1684x_f16_16b.bmodel --text_model ./models/BM1684X/clip_text_vitb32_bm1684x_f16_4b.bmodel --save_path ./results/embeddings.pkl --max_que_size 128 --dev_id 0
Traceback (most recent call last):
  File "embeddings_bmcv.py", line 10, in <module>
    from clip import CLIP_Multi
  File "/home/XXX/projects/python/CLIP-TPU/clip/__init__.py", line 10, in <module>
    from .clip import CLIP
  File "/home/XXX/projects/python/CLIP-TPU/clip/clip.py", line 21, in <module>
    import sophon.sail as sail
ImportError: /opt/sophon/sophon-ffmpeg-latest/lib/libavcodec.so.58: undefined symbol: bmvpu_malloc_device_byte_heap
```
怀疑是版本问题。
我的python版本为：Python 3.7.0 ；
/opt/sophon下的文件为：
![image](https://github.com/wangyifan2018/CLIP-TPU/assets/170588746/ca68476f-f3e1-48c4-b211-1d8ac62f00f9)
是从下面的链接下载得到的：
![image](https://github.com/wangyifan2018/CLIP-TPU/assets/170588746/0d3297b7-64a3-4c35-920a-d9bacd83482c)

我该如何解决上面的报错？是版本的问题吗？

**Comment by wangyifan2018** [comment]
是的，libsophon和sophon-mw版本太新了，用官网的稳定版本都是可以的，我的测试环境是
<img width="824" alt="image" src="https://github.com/wangyifan2018/CLIP-TPU/assets/44761289/d0cda57e-b92e-43ad-b495-7c1701f04648">
https://developer.sophgo.com/site/index/material/41/all.html
